//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XemPhimTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int subscriptionid { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<bool> state { get; set; }
        public int subscriptionpackageid { get; set; }
    
        public virtual SubscriptionPackage SubscriptionPackage { get; set; }
        public virtual User User { get; set; }
    }
}
